# Generated by Django 4.2 on 2026-10-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Luxury Double Bed', max_length=150)),
                ('price', models.IntegerField(help_text='Price in PKR')),
                ('size', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Queen', 'Queen'), ('King', 'King')], default='Double', max_length=50)),
                ('image_url', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bed',
                'verbose_name_plural': 'Beds',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('cell', models.CharField(max_length=30)),
                ('day', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('bed_detail', models.CharField(max_length=200)),
                ('total_amount', models.CharField(max_length=50)),
                ('delivery_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bed booking',
                'verbose_name_plural': 'Bed bookings',
            },
        ),
    ]
